feat(mutators) Avoid creating some unnecessary mutators for (a && b) …
stryker-mutator/stryker-js pull request #3346
Opened 2022-01-08 23:01 UTC by edi9999

Fix #3339

Will be adding a few comments inline

2022-01-11 06:49 UTC, nicojs requested changes
Looks incredibly simple if you put it like this 🙂

Got some small remarks. Also CI is failing

2022-01-11 06:49 UTC, nicojs commented on packages/instrumenter/test/unit/mutators/conditional-expression-mutator.spec.ts
> +  it('should mutate (c1 || c2 || c3)', () => {
This test ist failing in CI

2022-01-11 06:49 UTC, nicojs commented on packages/instrumenter/test/helpers/expect-mutation.ts
> +  mutants.sort();
Good idea!

2022-01-11 06:49 UTC, nicojs commented on packages/instrumenter/src/mutators/conditional-expression-mutator.ts
> +      if (path.parent && path.parent.type === 'LogicalExpression') {
Can we use optional chaining here? `path.parent?.type === 'LogicalExpression'`

2022-01-14 20:53 UTC, nicojs commented
> Maybe this test should simply be removed from this pull request, and a new issue created for this issue.

Yes, that's probably best. Probably a good idea to discuss it in a separate issue as well, as I think the test cases are already covered largely by the `logicalOperatorMutator`

2022-01-16 11:24 UTC, edi9999 commented
@nicojs  is there a way to update the e2e tests quickly ?

I'm running : 

```
npm run e2e
```

Since it stops after the first fail, I have to manually relaunch the tests and copy paste the output.

2022-01-16 17:24 UTC, nicojs commented
You can run them manually by running `npm test` in an e2e/test/xxx directory. But every time you change something in Stryker, you need to reinstall with `npm install` from the e2e root dir

2022-01-17 10:59 UTC, edi9999 commented
Tests are now passing, can you please review @nicojs ?

2022-01-17 16:39 UTC, nicojs approved these changes
LGTM 👍

2022-01-17 20:51 UTC, merged