feat: Accept hidden config file.
stryker-mutator/stryker-js pull request #3457
Opened 2022-03-05 20:39 UTC by regseb

Accept hidden files (starting with a dot) for configuration. Configuration files are often hidden files (such as _.mocharc.js_ or _.eslintrc.js_).

With this pull request, the `stryker.conf.(json|js|mjs|cjs)` and `.stryker.conf.(json|js|mjs|cjs)` files are searched by default.

2022-03-06 08:27 UTC, nicojs commented
Thanks for the PR.

Out of curiosity, what is the reason you would want your config in hidden files?

2022-03-06 08:55 UTC, regseb commented
When a new contributor joins the project, it's very often to fix a bug or to add a feature. It's rarely to modify the tooling (lint, test, build or release). By hiding the configuration files (_.git_, _.github_, _.editorconfig_, _.eslintrc.js_, _.gitignore_, _.mocharc.js_, ...), the contributor sees only the files directly related to the program.

2022-03-06 12:21 UTC, nicojs commented
Ah, is that the reason? Kind of makes sense, maybe. I always configure hidden files to be visible, so I wondered why.

2022-03-06 12:22 UTC, nicojs requested changes
This looks good.

Please also add unit and integration tests to the `core` package. And the `docs` directory contains the docs for the website; please add an explanation about this feature to the `config-file.md` there.

2022-03-06 14:07 UTC, regseb commented
@nicojs I added unit tests and a description in the documentation.

2022-03-07 08:58 UTC, nicojs approved these changes

2022-03-07 12:31 UTC, merged

2022-03-07 12:33 UTC, nicojs commented
Thanks @regseb 

Would you mind also opening a PR here: https://github.com/vscode-icons/vscode-icons/

Since I just got [the PR merged for `stryker.conf.x` files](https://github.com/vscode-icons/vscode-icons/pull/2896) 😅

2022-03-07 13:46 UTC, regseb commented
Pull request created: https://github.com/vscode-icons/vscode-icons/pull/2951

2022-03-07 17:59 UTC, nicojs commented
Thanks a lot! 👍

Feel free to scout around for other issues you want to fix 😁