Add emojis by default to clear-text-report
stryker-mutator/stryker-js pull request #3820
Opened 2022-10-29 10:56 UTC by brdv

Resolves #1189 

- Added emojis to CLI reports by default.
- Added option 'disableConsoleEmojis' to remove emojis if wanted

2022-10-29 10:57 UTC, nicojs commented on packages/core/package.json
> +    "emoji-regex": "^10.2.1",
Should be a `~`

2022-10-29 11:02 UTC, nicojs commented on packages/core/src/reporters/clear-text-score-table.ts
> +  private get headerLenght() {
Typo: `headerLength`

2022-10-29 11:07 UTC, brdv commented on packages/core/src/reporters/clear-text-score-table.ts
> +import emojiRegex from 'emoji-regex';
I think so, because we still have to check if there is a emoji in the header (it's used in private get headerLength)

2022-10-29 20:50 UTC, nicojs requested changes
Hard work is paying off 💪. I've got some small remarks. Would you mind changing it?

2022-10-29 20:50 UTC, nicojs commented on packages/api/schema/stryker-core.json
> +    "enableConsoleEmojis": {
I just now realize that we _do have console options_ here: https://github.com/stryker-mutator/stryker-js/blob/4e5600731cb6c62dfd64cf9b109b0521f342e391/packages/api/schema/stryker-core.json#L61. Would you mind adding it there under the name `allowEmojis` (default false).

2022-10-29 20:50 UTC, nicojs commented on packages/api/schema/stryker-core.json
> +      "description": "The 'enableConsoleEmojis' options adds emojis from the console (experimental).",
Suggestion: 'Enable emojis in your clear text report (experimental).'

2022-10-29 20:50 UTC, nicojs commented on packages/core/src/reporters/clear-text-reporter.ts
> +  private getStatusStringForMutant(mutant: MutantModel): string {
Suggestion: `statusLabel`. The fact that it is for a mutant is communicated by the parameter type 🤷‍♀️

2022-10-29 20:50 UTC, nicojs commented on packages/core/src/utils/string-utils.ts
> +export function inputLength(input: string): number {
I've thought about this name, probably `stringWidth` is a better name here. It communicates better the difference from the `.length` property.

2022-10-29 20:50 UTC, nicojs commented on packages/core/src/stryker-cli.ts
> +      .option('--enableConsoleEmojis', 'Choose whether or not emoji will be shown in CLI output. Default option is false.')
Since we're calling it an experimental feature, let's not put it as a cli argument for now.

2022-10-30 16:28 UTC, nicojs approved these changes
Thanks a lot! This is a dlighted new feature that I hope we can enable by default in the future.  😍

2022-10-30 16:30 UTC, merged

2022-10-30 21:29 UTC, nicojs commented
Released in `6.3.0` 🎉

If you want you can also create a PR to document these console reporter options, they seem to be missing from https://stryker-mutator.io/docs/stryker-js/configuration/

2022-10-30 21:33 UTC, nicojs commented
See #3827