Mutant Worker Id
stryker-mutator/stryker-js pull request #3821
Opened 2022-10-29 12:37 UTC by ariba-05

Fixes #3231

2022-10-29 13:00 UTC, nicojs requested changes
This is great stuff! Got some remarks.

2022-10-29 14:45 UTC, nicojs commented on packages/core/src/child-proxy/child-process-proxy.ts
> +      env: { STRYKER_MUTATOR_WORKER: workerId },
```suggestion
      env: { STRYKER_MUTATOR_WORKER: workerId,  ...process.env },
```

We shouldn't forget to also pass along the `process.env` of the parent process.

2022-10-30 11:09 UTC, ariba-05 commented on packages/core/test/unit/checker/checker-child-process-proxy.spec.ts
> +    idGenerator = new IdGenerator();
I've made similar changes in `child-process-proxy.spec.ts`. Could you pls review if I've done it correctly as you suggested?

2022-10-30 14:20 UTC, ariba-05 commented
I can't seem to find the root cause of time out error in the CI e2e tests (https://github.com/stryker-mutator/stryker-js/actions/runs/3351682875/jobs/5553525949)9). The e2e test errors I get in my local setup are different. I've pushed everything else. @nicojs , could you please maybe trigger the workflow again to see if the errors are the same now or does it have something to do with slow network? :/

2022-10-30 16:21 UTC, nicojs commented on packages/core/src/test-runner/index.ts
> +  'worker-id-generator'
```suggestion
  coreTokens.workerIdGenerator 
```

2022-10-30 16:23 UTC, nicojs commented on packages/core/test/unit/child-proxy/id-generator.spec.ts
> +  it('should increment workerId on calling `next`', async () => {
Since we control the SUT (System Under Test, namely the `IdGenerator` class), we can test that the first call to `next` provides the value `0`.

2022-10-30 16:25 UTC, nicojs approved these changes
Wow, this looks great! You did a great job. Just 2 nit remarks. I'll merge it later tonight if you don't have time to fix them 👍.

2022-10-30 16:37 UTC, ariba-05 commented
Made the changes, @nicojs. Thanks for the review and helping me through my _first_ open source contribution 😄

2022-10-30 21:20 UTC, nicojs approved these changes
Looks good to me!

2022-10-30 21:22 UTC, merged

2022-10-30 21:46 UTC, nicojs commented
I've released this feature in 6.3 🎉
https://github.com/stryker-mutator/stryker-js/releases/tag/v6.3.0

This feature still needs documentation. I've opened #3828 for it. Feel free to pick it up if you want 😉

2022-10-30 21:59 UTC, nicojs commented on packages/core/test/unit/checker/checker-child-process-proxy.spec.ts
> +    idGenerator = new IdGenerator();
Yes, that is good 👌

2022-10-30 22:02 UTC, nicojs commented
> Thanks for the review and helping me through my _first_ open source contribution 😄

The first of many, I hope 🤝. My pleasure; you are a fast learner. Keep it up! 🤗