Remove non-existent file data from mutation test results
stryker-mutator/stryker-js pull request #4134
Opened 2023-04-22 14:10 UTC by mkizka

fix: https://github.com/stryker-mutator/stryker-js/issues/4085
Hello. I have read the CONTRIBUTING.md, but please let me know if there are any mistakes.

2023-04-23 10:18 UTC, nicojs commented
@mkizka, thanks for picking this one up!

I was thinking this should be fixed in the `incremental-differ.ts` file instead. The `IncrementalDiffer` is responsible for diffing the incremental report json file with the project's current status (discovered during the initial test run). 

It apparently keeps deleted test files in the report. You can fix that by applying this code change:

```diff
@@ -242,13 +242,9 @@ export class IncrementalDiffer {
             byKey.set(key, testInfo);
           });
         } else {
-          // No sources to compare, we should do our best with the info we do have
-          oldTestFile.tests.map((test) => {
-            const key = testToIdentifyingKey(test, relativeFileName);
-            const testInfo = { key, test, relativeFileName };
-            byId.set(test.id, testInfo);
-            byKey.set(key, testInfo);
-          });
+          // No sources to compare to, test file is removed.
+          log.debug('Test file removed: %s', relativeFileName);
+          testStatisticsCollector.count(relativeFileName, 'removed', oldTestFile.tests.length);
         }
       });
```

After that, some tests are failing; my guess is because of incorrect test data. Do you think you feel up to the task?

2023-04-23 10:18 UTC, nicojs requested changes
See my comment.

2023-04-23 13:03 UTC, mkizka commented
Wow, this change looks better. I'll try to fix.

2023-04-24 21:07 UTC, nicojs requested changes
Wow, an awesome job so far! Tests green with small tweaks 👍

Could you also add a test for e test file that is removed?

2023-04-24 21:07 UTC, nicojs commented on packages/core/src/mutants/incremental-differ.ts
> +        } else if (currentFileSource !== undefined && oldTestFile.source !== undefined) {
I'm missing new unit tests for these:

![image](https://user-images.githubusercontent.com/1828233/234116940-40a2f886-2927-44d3-836c-9dd925420eee.png)

2023-04-25 15:34 UTC, mkizka commented
Thanks for your review. I have added the test.
About the fileName, what is the situation that it is empty? Should I add a test for this too?
```js
if (currentFileSource === undefined && fileName !== '') {
```

2023-05-04 13:54 UTC, nicojs commented
> Thanks for your review. I have added the test. About the fileName, what is the situation that it is empty? Should I add a test for this too?
> 
> ```js
> if (currentFileSource === undefined && fileName !== '') {
> ```

This happens for example, when using the karma runner. It reports the tests without the file from which they originated. In that case, the JSON contains something like this:

```json
{
"testFiles": {
    "": {
      "tests": [
        { "id": "0", "name": "Add should be able to add two numbers" },
        { "id": "1", "name": "Add should be able 1 to a number" },
        { "id": "2", "name": "Add should be able negate a number" },
        { "id": "3", "name": "Add should be able to recognize a negative number" },
        { "id": "4", "name": "Add should be able to recognize that 0 is not a negative number" },
        { "id": "5", "name": "Circle should have a circumference of 2PI when the radius is 1" }
      ]
    }
  }
}
```

You're currently missing a test case for precisely that:

![image](https://user-images.githubusercontent.com/1828233/236225778-0bbe61cf-ead6-4310-94f4-b7e530e58577.png)

Since it is a big part of the feature set, would you mind adding a test for that as well?

2023-05-04 15:41 UTC, mkizka commented
I understand. I have added one more test.

2023-05-05 20:22 UTC, nicojs approved these changes

2023-05-05 20:42 UTC, merged