set NODE_ENV to test in vitest runner
stryker-mutator/stryker-js pull request #4290
Opened 2023-06-11 13:19 UTC by rluvaton

fix #4289

I would like to add tests but I'm not really sure how, there are a lot of configuration needed, and coping from the jest test miss some things

2023-06-12 06:45 UTC, nicojs requested changes
Thanks for this PR! 🙏

I think it's OK to add a unit test for this. When you set the env in `init`, you can simply add a unit test to it in "test/unit/vitest-runner.spec.ts".

2023-06-12 06:45 UTC, nicojs commented on packages/vitest-runner/src/vitest-test-runner.ts
> +    this.setEnv();
I think this could be set in `.init()`, instead of `run`.

2023-06-14 10:13 UTC, rluvaton commented
I will try to update later this, week, thanks

2023-06-16 09:08 UTC, rluvaton commented
Hey @nicojs , there are a lot of missing things in the `createVitestMock` like `projects` and `state`, is there a reason to create these unit tests?

I tried to avoid unit tests and focus on component tests to reduce the number of changes I need to do in the tests when I do a refactor

2023-06-16 09:16 UTC, rluvaton commented
added the test and moved the set env to init

2023-06-16 15:11 UTC, nicojs commented on packages/vitest-runner/test/unit/vitest-runner.spec.ts
> +    expect(process.env.NODE_ENV).to.not.equal('test');
Maybe it's better to delete it?

```js
delete process.env.NODE_ENV;
```

2023-06-16 15:31 UTC, rluvaton commented
> > is there a reason to create these unit tests
> 
> Generally, everything should be tested as low in the testing pyramid as possible. If at all possible. In this case it is possible, so yes, probably a unit test.

I tend to disagree, component tests are much easier to write (as you come from the user point of view) and cover much more while also protecting you from changing the tests when doing refactor across units

(IMO)


Take a look at:
- https://github.com/testjavascript/nodejs-integration-tests-best-practices
- https://kentcdodds.com/blog/the-testing-trophy-and-testing-classifications

2023-06-16 15:33 UTC, rluvaton commented on packages/vitest-runner/test/unit/vitest-runner.spec.ts
> +    expect(process.env.NODE_ENV).to.not.equal('test');
agree, done

2023-06-16 20:05 UTC, nicojs approved these changes

2023-06-16 20:52 UTC, merged

2023-06-17 17:55 UTC, rluvaton commented
Hope to contribute to this project again soon!

It was great working with you!